name: First CICD Pipeline

on:
   push:
    branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Copy name to machine
              uses: actions/checkout@v4
            - name: Logining In to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{vars.DOCKER_USERNAME}}
                  password: ${{secrets.DOCKERHUB_TOKEN}}
            - name: Pull and and push to docker Hub
              working-directory: ./bisi
              run: |
                docker build -t ${{vars.DOCKER_USERNAME}}/ndubuisi .
                docker push ${{vars.DOCKER_USERNAME}}/ndubuisi
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Deploy our server
              uses: appleboy/ssh-action@master
              with:
                host: ${{secrets.EC2_HOST_SERVER}}
                username: ${{secrets.EC2_USERNAME}}
                key: ${{secrets.EC2_PRIVATE_KEY}}
                script: |
                  sudo docker pull ${{vars.DOCKER_USERNAME}}/ndubuisi
                  sudo docker rm -f wow
                  sudo docker run -d --name ndubuisi ${{vars.DOCKER_USERNAME}}/ndubuisi